name: vfx2022

on:
  workflow_dispatch:

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    container:
      image: 'aswf/ci-base:2022'
      volumes:
        - /node20217:/node20217:rw,rshared
        - /node20217:/__e/node20:ro,rshared

    steps:
      - name: install nodejs20glibc2.17
        run: |
          curl --silent https://unofficial-builds.nodejs.org/download/release/v20.18.1/node-v20.18.1-linux-x64-glibc-217.tar.xz | \
            tar -xJ --strip-components 1 -C /node20217 -f -
          ldd /__e/node20/bin/node

      - name: demonstrate actions working
        uses: actions/checkout@v4

      - name: show environment
        run: |
          echo "#### README.md #####################"
          cat README.md
          echo "#### redhat-release ################"
          cat /etc/redhat-release
          echo "#### gcc location ##################"
          which gcc
          echo "#### gcc version ###################"
          gcc -v
